checks:
    javascript: true
build:
    environment:
        node: 22
    dependencies:
        override:
            - npm ci
    nodes:
        analysis:
            tests:
                override:
                    - js-scrutinizer-run
        coverage:
            tests:
                override:
                    - command: npx vitest run --coverage --project unit
                      coverage:
                          file: coverage/clover.xml
                          format: clover
