ignore:
  - "stories/**/*"
  - "\\.storybook/**/*"
  - "vite\\.config\\.ts"
  - "vitest\\.config\\.ts"
  - "vitest\\.shims\\.d\\.ts"
  - "src/test/**/*"
  - "src/templates/shared/types\\.ts"
  - "src/types/types\\.ts"
  - "src/types/isGroup\\.ts"
